#ifndef BRINGUP_MANIFEST_GEN_H
#define BRINGUP_MANIFEST_GEN_H

/* Generated by tools/bringup_compile.py. Do not edit manually. */

#ifdef BRINGUP_MANIFEST_INCLUDE_PHASE_SECTION

typedef struct {
  const char *name;
  BringupStageId stage;
} BringupManifestPhaseDef;

typedef struct {
  const char *alias;
  BringupPhaseId phase;
} BringupManifestPhaseAliasDef;

typedef struct {
  const char *name;
  const char *entry_event;
  const char *exit_event;
  BringupPhaseId phase_begin;
  BringupPhaseId phase_end;
} BringupManifestStageDef;

typedef struct {
  const char *alias;
  BringupStageId stage;
} BringupManifestStageAliasDef;

#define BRINGUP_MANIFEST_PHASE_ALIAS_COUNT 19U
#define BRINGUP_MANIFEST_STAGE_ALIAS_COUNT 1U

static const BringupManifestPhaseDef bringup_manifest_phase_defs[BRINGUP_PHASE_COUNT] = {
  [BRINGUP_PHASE_ROM_EARLY_INIT] = { "rom-early-init", BRINGUP_STAGE_INIT },
  [BRINGUP_PHASE_MPU_SETUP] = { "mpu-setup", BRINGUP_STAGE_MPU },
  [BRINGUP_PHASE_KERNEL_START] = { "kernel-start", BRINGUP_STAGE_KERNEL },
  [BRINGUP_PHASE_DRIVER_PROBE_DIAG] = { "driver-probe-diag", BRINGUP_STAGE_DRIVERS },
  [BRINGUP_PHASE_DRIVER_PROBE_UART] = { "driver-probe-uart", BRINGUP_STAGE_DRIVERS },
  [BRINGUP_PHASE_DRIVER_PROBE_SENSOR] = { "driver-probe-sensor", BRINGUP_STAGE_DRIVERS },
  [BRINGUP_PHASE_DRIVER_PROBE_VM] = { "driver-probe-vm", BRINGUP_STAGE_DRIVERS },
  [BRINGUP_PHASE_SERVICE_REGISTRATION] = { "service-registration", BRINGUP_STAGE_DRIVERS },
  [BRINGUP_PHASE_USER_WORKLOAD_ENABLE] = { "user-workload-enable", BRINGUP_STAGE_READY },
};

static const BringupManifestPhaseAliasDef bringup_manifest_phase_alias_defs[BRINGUP_MANIFEST_PHASE_ALIAS_COUNT] = {
  { "rom", BRINGUP_PHASE_ROM_EARLY_INIT },
  { "early", BRINGUP_PHASE_ROM_EARLY_INIT },
  { "mpu", BRINGUP_PHASE_MPU_SETUP },
  { "kernel", BRINGUP_PHASE_KERNEL_START },
  { "driver", BRINGUP_PHASE_DRIVER_PROBE_DIAG },
  { "probe", BRINGUP_PHASE_DRIVER_PROBE_DIAG },
  { "driver-probe", BRINGUP_PHASE_DRIVER_PROBE_DIAG },
  { "driver-diag", BRINGUP_PHASE_DRIVER_PROBE_DIAG },
  { "diag", BRINGUP_PHASE_DRIVER_PROBE_DIAG },
  { "driver-uart", BRINGUP_PHASE_DRIVER_PROBE_UART },
  { "uart", BRINGUP_PHASE_DRIVER_PROBE_UART },
  { "driver-sensor", BRINGUP_PHASE_DRIVER_PROBE_SENSOR },
  { "sensor", BRINGUP_PHASE_DRIVER_PROBE_SENSOR },
  { "driver-vm", BRINGUP_PHASE_DRIVER_PROBE_VM },
  { "vm", BRINGUP_PHASE_DRIVER_PROBE_VM },
  { "service", BRINGUP_PHASE_SERVICE_REGISTRATION },
  { "services", BRINGUP_PHASE_SERVICE_REGISTRATION },
  { "user", BRINGUP_PHASE_USER_WORKLOAD_ENABLE },
  { "workload", BRINGUP_PHASE_USER_WORKLOAD_ENABLE },
};

static const BringupManifestStageDef bringup_manifest_stage_defs[BRINGUP_STAGE_COUNT] = {
  [BRINGUP_STAGE_INIT] = { "init", "bringup.stage.init.enter", "bringup.stage.init.exit", BRINGUP_PHASE_ROM_EARLY_INIT, BRINGUP_PHASE_ROM_EARLY_INIT },
  [BRINGUP_STAGE_MPU] = { "mpu", "bringup.stage.mpu.enter", "bringup.stage.mpu.exit", BRINGUP_PHASE_MPU_SETUP, BRINGUP_PHASE_MPU_SETUP },
  [BRINGUP_STAGE_KERNEL] = { "kernel", "bringup.stage.kernel.enter", "bringup.stage.kernel.exit", BRINGUP_PHASE_KERNEL_START, BRINGUP_PHASE_KERNEL_START },
  [BRINGUP_STAGE_DRIVERS] = { "drivers", "bringup.stage.drivers.enter", "bringup.stage.drivers.exit", BRINGUP_PHASE_DRIVER_PROBE_DIAG, BRINGUP_PHASE_SERVICE_REGISTRATION },
  [BRINGUP_STAGE_READY] = { "ready", "bringup.stage.ready.enter", "bringup.stage.ready.exit", BRINGUP_PHASE_USER_WORKLOAD_ENABLE, BRINGUP_PHASE_USER_WORKLOAD_ENABLE },
};

static const BringupManifestStageAliasDef bringup_manifest_stage_alias_defs[BRINGUP_MANIFEST_STAGE_ALIAS_COUNT] = {
  { "driver", BRINGUP_STAGE_DRIVERS },
};

#endif

#ifdef BRINGUP_MANIFEST_INCLUDE_DEPENDENCY_SECTION

#define BRINGUP_MANIFEST_DEP_DRIVER_EDGE_COUNT 5U
#define BRINGUP_MANIFEST_DEP_RESOURCE_EDGE_COUNT 8U
#define BRINGUP_MANIFEST_DEP_STAGE_DRIVER_EDGE_COUNT 5U

static const DepDriverEdge bringup_manifest_dep_driver_edges[BRINGUP_MANIFEST_DEP_DRIVER_EDGE_COUNT] = {
  { KDI_DRIVER_UART, KDI_DRIVER_DIAG, "diagnostic log/control path" },
  { KDI_DRIVER_SENSOR, KDI_DRIVER_UART, "sensor telemetry uplink" },
  { KDI_DRIVER_VM_RUNTIME, KDI_DRIVER_UART, "vm io service channel" },
  { KDI_DRIVER_VM_RUNTIME, KDI_DRIVER_SENSOR, "vm consumes sensor data plane" },
  { KDI_DRIVER_VM_RUNTIME, KDI_DRIVER_DIAG, "vm fault trace routing" },
};

static const DepResourceEdge bringup_manifest_dep_resource_edges[BRINGUP_MANIFEST_DEP_RESOURCE_EDGE_COUNT] = {
  { KDI_DRIVER_UART, DEP_RESOURCE_IRQ, "USARTx_VCP", "uart rx/tx interrupt path" },
  { KDI_DRIVER_UART, DEP_RESOURCE_MEMORY, "g_shared_ctrl", "runtime knob sync" },
  { KDI_DRIVER_SENSOR, DEP_RESOURCE_DMA, "ADC_DMA_RING", "adc dma sample ingress" },
  { KDI_DRIVER_SENSOR, DEP_RESOURCE_MEMORY, "g_shared_adc", "sensor sample window" },
  { KDI_DRIVER_VM_RUNTIME, DEP_RESOURCE_MEMORY, "g_shared_adc", "vm sensor read mapping" },
  { KDI_DRIVER_VM_RUNTIME, DEP_RESOURCE_MEMORY, "g_shared_ctrl", "vm control mapping" },
  { KDI_DRIVER_VM_RUNTIME, DEP_RESOURCE_MEMORY, "g_shared_stats", "vm stats mapping" },
  { KDI_DRIVER_DIAG, DEP_RESOURCE_MEMORY, "log_queue", "diagnostic sink buffer" },
};

static const DepStageDriverEdge bringup_manifest_dep_stage_driver_edges[BRINGUP_MANIFEST_DEP_STAGE_DRIVER_EDGE_COUNT] = {
  { BRINGUP_PHASE_KERNEL_START, KDI_DRIVER_KERNEL, "kernel runtime online" },
  { BRINGUP_PHASE_DRIVER_PROBE_DIAG, KDI_DRIVER_DIAG, "diag probe/activate" },
  { BRINGUP_PHASE_DRIVER_PROBE_UART, KDI_DRIVER_UART, "uart probe/activate" },
  { BRINGUP_PHASE_DRIVER_PROBE_SENSOR, KDI_DRIVER_SENSOR, "sensor probe/activate" },
  { BRINGUP_PHASE_DRIVER_PROBE_VM, KDI_DRIVER_VM_RUNTIME, "vm probe/activate" },
};

#endif

#endif
